import { Background } from "@/components/background/Background";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-full max-h-screen relative z-50 bg-gray-950/90">
        {children}
        <Background />
      </body>
    </html>
  );
}
